### ISSUE TITLE
simple example does not work

### ISSUE THREAD

**Issue by mguterl** [hybridgroup/taskmapper-unfuddle#5]
Just trying out some stuff from the ticketmaster README and it's failing.

```
require 'ticketmaster'
require 'ticketmaster-unfuddle'

unfuddle = TicketMaster.new(:unfuddle, {:username => "XXXXXX", :password => "XXXXXX", :account => "XXXXXX"})
project  = unfuddle.project("IT")

ActiveResource::Redirection: Failed.  Response code = 302.  Response message = Found. => https://recruitmilitary.unfuddle.com/projects/IT
from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.02@tickets/gems/activeresource-3.0.3/lib/active_resource/connection.rb:125:in `handle_response'
from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.02@tickets/gems/activeresource-3.0.3/lib/active_resource/connection.rb:114:in `request'
from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.02@tickets/gems/activeresource-3.0.3/lib/active_resource/connection.rb:79:in `get'
from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.02@tickets/gems/activeresource-3.0.3/lib/active_resource/connection.rb:217:in `with_auth'
from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.02@tickets/gems/activeresource-3.0.3/lib/active_resource/connection.rb:79:in `get'
from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.02@tickets/gems/activeresource-3.0.3/lib/active_resource/base.rb:881:in `find_single'
from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.02@tickets/gems/activeresource-3.0.3/lib/active_resource/base.rb:781:in `find'
from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.02@tickets/gems/ticketmaster-0.5.2/lib/ticketmaster/project.rb:89:in `find_by_id'
from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.02@tickets/gems/ticketmaster-0.5.2/lib/ticketmaster/project.rb:71:in `find'
from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.02@tickets/gems/ticketmaster-0.5.2/lib/ticketmaster/helper.rb:10:in `easy_finder'
from /Users/michaelguterl/.rvm/gems/ree-1.8.7-2010.02@tickets/gems/ticketmaster-0.5.2/lib/ticketmaster/provider.rb:36:in `project'
from (irb):12
```

**Comment by kiafaldorius** [comment]
Hi! Thanks for the README patch.

You may need to add :protocol => 'https' to the options:

```
unfuddle = TicketMaster.new(:unfuddle, :username => "XXXXXX", :password => "XXXXXX", :account => "XXXXXX", :protocol => 'https')
```

Thanks

**Comment by mguterl** [comment]
Thanks, that works great!  Great stuff you have here, I can't wait to dig in some more.
